server:
  port: 88
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: gulimall-product
          uri: lb://gulimall-product
          predicates:
            - Path=/gulimall-product/**
          filters:
            - StripPrefix=1
        - id: gulimall-third-party
          uri: lb://gulimall-third-party
          predicates:
            - Path=/gulimall-third-party/**
          filters:
            - StripPrefix=1
        - id: gulimall-admin
          uri: lb://gulimall-admin
          predicates:
            - Path=/gulimall-admin/**
          filters:
            - StripPrefix=1

###前段项目,/api
##http://localhost:88/api/captcha.jpg   http://localhost:8080/renrenfast/captcha.jpg
##http://localhost:88/api/product/category/list/tree  http://localhost:11000/product/category/list/tree
